dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.17.2/bazel_0.17.2-linux-x86_64.deb
  - sudo dpkg --force-all -i bazel_0.17.2-linux-x86_64.deb
  - sudo apt-get install -y liblz4-dev

script:
- bazel build @com_github_facebook_zstd//...
